services:
    # Controllers
    Adlarge\FixturesDocumentationBundle\Controller\FixturesDocumentationController:
        public: true
        autowire: true
        arguments:
            $docTitle: '%adlarge_fixtures_documentation.title%'
            $reloadCommands: '%adlarge_fixtures_documentation.reloadCommands%'

    # Managers
    Adlarge\FixturesDocumentationBundle\Service\FixturesDocumentationManager:
        public: true
        autowire: true
        arguments:
            $projectDir: '%kernel.project_dir%'
            $reloadCommands: '%adlarge_fixtures_documentation.reloadCommands%'
            $configEntities: '%adlarge_fixtures_documentation.configEntities%'
            $fileDest: '%adlarge_fixtures_documentation.fileDest%'

    # Listeners
    Adlarge\FixturesDocumentationBundle\EventListener\FixturesDocumentationListener:
        public: true
        arguments:
            $fixturesDocumentationManager: '@Adlarge\FixturesDocumentationBundle\Service\FixturesDocumentationManager'
            $listenedCommand: '%adlarge_fixtures_documentation.listenedCommand%'
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandExecution }
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateExecution }

    Adlarge\FixturesDocumentationBundle\EventListener\DoctrineListener:
        public: true
        arguments:
            $documentationManager: '@Adlarge\FixturesDocumentationBundle\Service\FixturesDocumentationManager'
            $enableAutoDocumentation: '%adlarge_fixtures_documentation.enableAutoDocumentation%'
        tags:
            - { name: doctrine.event_listener, event: postPersist}
